require_relative './config/environment'
require 'sinatra/activerecord/rake'

desc "Start our app console"
task :console do
  Pry.start
end

# desc "Greets the user"
# task :greet do
#   puts "Welcome to our program"
# end
